services:
  jenkins:
    build: ./jenkins
    image: jenkins
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - eureka-data:/eureka-deploy
      - users-data:/users-deploy
      - client-services-data:/client-services-deploy
      - tourism-services-data:/tourism-services-deploy
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - micro-travels-net


  eureka: 
    build: ./eureka
    container_name: eureka
    networks:
      - micro-travels-net
    ports:
      - 8761:8761
      - 9990:9990
      - 2220:2220
    volumes:
      - eureka-data:/web-apps
    environment:
      - eureka.instance.preferIpAddress=true
    
  users-server:
    build: ./users
    image: tomcat
    container_name: users
    volumes:
      - users-data:/usr/local/tomcat/webapps
    ports:
      - 8081:8080
    environment: 
      - TOMCAT_PASSWORD=tomcat
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - server.port=8080
    depends_on:
      - "eureka"
    networks:
      - micro-travels-net

  client-services-server:
    build: ./clientServices
    image: tomcat
    container_name: client-services
    volumes:
      - client-services-data:/usr/local/tomcat/webapps
    ports:
      - 8082:8080
    environment: 
      - TOMCAT_PASSWORD=tomcat
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - server.port=8080
    depends_on:
      - "eureka"
    networks:
      - micro-travels-net

  tourism-services-server:
    build: ./tourismServices
    image: tomcat
    container_name: tourism-services
    volumes:
      - tourism-services-data:/usr/local/tomcat/webapps
    ports:
      - 8083:8080
    environment: 
      - TOMCAT_PASSWORD=tomcat
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
      - eureka.instance.preferIpAddress=true
      - server.port=8080
      - soap.url=http://eureka:2220/ws
    depends_on:
      - "eureka"
    networks:
      - micro-travels-net

networks:
  micro-travels-net:
    driver: bridge

volumes:
  jenkins-data:
  eureka-data:
  client-services-data:
  tourism-services-data:
  users-data:
