services:
  jenkins:
    build: ./jenkins
    image: jenkins
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - entrypoint-data:/entrypoint-deploy
      - users-data:/users-deploy
      - client-services-data:/client-services-deploy
      - tourism-services-data:/tourism-services-deploy
    ports:
      - 8080:8080
    networks:
      - micro-travels-net

  eureka:
     eureka: 
        build: ./eureka
        container_name: eureka
        networks:
            - micro-travels-net
        ports:
            - 8761:8761

  entrypoint-server:
    build: ./entryPoint
    image: tomcat
    container_name: entrypoint
    volumes:
      - entrypoint-data:/usr/local/tomcat/webapps
    ports:
      - 8081:8080
    environment: 
      - TOMCAT_PASSWORD=tomcat
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - "eureka"
    networks:
      - micro-travels-net
    
  users-server:
    build: ./users
    image: tomcat
    container_name: users
    volumes:
      - users-data:/usr/local/tomcat/webapps
    ports:
      - 8082:8080
    environment: 
      - TOMCAT_PASSWORD=tomcat
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - "eureka"
    networks:
      - micro-travels-net

  client-services-server:
    build: ./clientServices
    image: tomcat
    container_name: client-services
    volumes:
      - client-services-data:/usr/local/tomcat/webapps
    ports:
      - 8083:8080
    environment: 
      - TOMCAT_PASSWORD=tomcat
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - "eureka"
    networks:
      - micro-travels-net

  tourism-services-server:
    build: ./tourismServices
    image: tomcat
    container_name: tourism-services
    volumes:
      - tourism-services-data:/usr/local/tomcat/webapps
    ports:
      - 8084:8080
    environment: 
      - TOMCAT_PASSWORD=tomcat
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/
    depends_on:
      - "eureka"
    networks:
      - micro-travels-net

networks:
  micro-travels-net:
    driver: bridge

volumes:
  jenkins-data:
  entrypoint-data:
  client-services-data:
  tourism-services-data:
  users-data:
