server:
    port: 8888

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway


spring:
    application.name: gateway 
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: users-id
                  uri: lb://user-service
                  predicates:
                      - Path=/users/**
                      - Method=GET,PUT,DELETE
                  filters:
                    - AuthFilter  
                - id: users-signin-id
                  uri: lb://user-service
                  predicates:
                      - Path=/login, /users/**
                      - Method=POST
                    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka